#!/bin/env python3

import os
import sys
sys.path.append('./build/lib/')

from qtpy import QtCore, QtWidgets
from astrojc.gui.qt_2dimage_plotter import HDUFigureCanvas2D
from astrojc.gui.qt_fitsfiletree import HDUFileSystemModel
from astrojc.gui.qt_fitstable import HDUTableWidget

from astropy.io import fits

class ViewWidget(QtWidgets.QTabWidget):
    def __init__(self, parent=None):
        super(QtWidgets.QTabWidget, self).__init__(parent)
        self.setTabsClosable(True)

    def add_hdu_tab(self, hdu, name):
        if isinstance(hdu, (fits.PrimaryHDU, fits.ImageHDU)):
            self.addTab(HDUFigureCanvas2D(hdu, self), name)
        elif isinstance(hdu, (fits.BinTableHDU, fits.TableHDU)):
            self.addTab(HDUTableWidget(hdu, self), name)

class FitsExplorerMW(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(QtWidgets.QMainWindow, self).__init__(parent)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        self.setWindowTitle('FitsExplorer')

        self.setMinimumSize(800, 600)

        self.create_file_tree()
        self.create_fits_viewer()
        self.create_layout()

    def create_file_tree(self, root=None):
        if root is None:
            root = ''
        self.file_tree = HDUFileSystemModel(root, self)

    def create_fits_viewer(self):
        self.fits_viewer = ViewWidget(self)

    def create_layout(self):
        self.main_widget = QtWidgets.QWidget(self)
        self.layout = QtWidgets.QHBoxLayout(self.main_widget)
        self.layout.addWidget(self.file_tree)
        self.layout.addWidget(self.fits_viewer)
        self.main_widget.setFocus()
        self.setCentralWidget(self.main_widget)

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setApplicationName('FitsExplorer')

    mw = FitsExplorerMW()

    hdu = fits.open('/home/julio/SP_I_0017.fits')[0]
    hdut = fits.open('/home/julio/Test2.fits')[1]

    mw.fits_viewer.add_hdu_tab(hdu, 'testing image')
    mw.fits_viewer.add_hdu_tab(hdut, 'testing table')

    mw.show()

    sys.exit(app.exec_())
