#!/bin/env python3

import os
import sys
sys.path.append('./build/lib/')

from qtpy import QtCore, QtWidgets
from astrojc.gui.qt_2dimage_plotter import HDUFigureCanvas2D
from astrojc.gui.qt_fitsfiletree import HDUFileSystemModel
from astrojc.gui.qt_fitstable import HDUTableWidget

from astropy.io import fits

class ViewWidget(QtWidgets.QTabWidget):
    def __init__(self, parent=None):
        super(QtWidgets.QTabWidget, self).__init__(parent)
        self.setTabsClosable(True)

    def add_hdu_tab(self, hdu, name):
        if isinstance(hdu, (fits.PrimaryHDU, fits.ImageHDU)):
            self.addTab(HDUFigureCanvas2D(hdu, self), name)
        elif isinstance(hdu, (fits.BinTableHDU, fits.TableHDU)):
            self.addTab(HDUTableWidget(hdu, self), name)

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    app.setApplicationName('FitsExplorer')

    mw = QtWidgets.QMainWindow()
    mw.setAttribute(QtCore.Qt.WA_DeleteOnClose)
    mw.setWindowTitle("FitsExplorer")

    folder = '/home/julio'
    hdu = fits.open('/home/julio/SP_I_0017.fits')[0]
    hdut = fits.open('/home/julio/Test2.fits')[1]
    hdu_tree = HDUFileSystemModel(folder, mw)
    tab_view = ViewWidget(mw)
    tab_view.add_hdu_tab(hdu, 'testing image')
    tab_view.add_hdu_tab(hdut, 'testing table')

    main_widget = QtWidgets.QWidget(mw)
    layout = QtWidgets.QHBoxLayout(main_widget)
    layout.addWidget(hdu_tree)
    layout.addWidget(tab_view)

    main_widget.setFocus()
    mw.setCentralWidget(main_widget)
    mw.show()

    sys.exit(app.exec_())
